---

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: local
  hooks:
    - id: gofmt
      name: Format w/ gofmt
      description: Runs `gofmt` on Go files
      language: system
      entry: gofmt -w
      types: [go]
